### Login - obtine token
POST http://localhost:8082/login?username=admin&password=admin123

### Solve fara token - ar trebui sa primesti 401
GET http://localhost:8082/solve?minSize=2

### Solve cu token - inlocuieste TOKEN_AICI cu tokenul primit de la login
GET http://localhost:8082/solve?minSize=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTc2NTE4MiwiZXhwIjoxNzc1NzY4NzgyfQ.mATJgm0QOYibY5N3FTaVC-ZUDrlxIlt6Z7fwUXj3cp0

